name: Deploy to server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to server
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          FILE: "acer-${{ github.ref_name }}.jar"
        run: |
          sftp -oPort=$SFTP_PORT -oStrictHostKeyChecking=no -b - $SFTP_USERNAME@$SFTP_HOST <<EOF
            rm mods/acer-*.jar
            put build/libs/$FILE mods/
          EOF